<a href="https://colab.research.google.com/github/dheaadventina/Hand-On-Proyek-EAS-PPS_Dhea-Adventina-Sandy/blob/main/Progress_Proyek_EAS_PPS_Dhea_Adventina_Sandy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nama: Dhea Adventina Sandy\
NIM: 2430209040008\
Mata Kuliah: Pengantar Proses Stokastik

Berikut merupakan implementasi program Python yang digunakan untuk membentuk matriks transisi dan menghitung distribusi stasioner pada model rantai Markov tingkat kehadiran mahasiswa.

In [1]:
import numpy as np

# ==========================================
# STATE
# ==========================================

states = ["Rajin Hadir", "Kadang Hadir", "Sering Absen"]

# ==========================================
# INPUT MATRIKS TRANSISI 3x3
# ==========================================

P = []

print("Masukkan probabilitas transisi:")

for i in range(3):

    print(f"\nDari state {states[i]}:")

    baris = []
    total = 0

    for j in range(3):
        p = float(input(f"Peluang ke {states[j]}: "))
        baris.append(p)
        total += p

    # Validasi jumlah probabilitas
    if abs(total - 1) > 0.0001:
        print("Jumlah probabilitas dalam satu baris harus = 1")
        exit()

    P.append(baris)

# Ubah menjadi array numpy
P = np.array(P)

# ==========================================
# TAMPILKAN MATRIKS
# ==========================================

print("\nMatriks Transisi:")
print(P)

# ==========================================
# HITUNG STEADY STATE
# ==========================================

A = P.T - np.eye(3)

# Tambah syarat jumlah probabilitas = 1
A = np.vstack((A, np.ones(3)))

b = np.array([0, 0, 0, 1])

# Penyelesaian SPL
steady_state = np.linalg.lstsq(A, b, rcond=None)[0]

# ==========================================
# OUTPUT
# ==========================================

print("\nDistribusi Stasioner:")

for i in range(3):
    print(f"{states[i]} = {steady_state[i]:.4f}")

Masukkan probabilitas transisi:

Dari state Rajin Hadir:
Peluang ke Rajin Hadir: 1
Peluang ke Kadang Hadir: 1.5
Peluang ke Sering Absen: 1.4
Jumlah probabilitas dalam satu baris harus = 1

Dari state Kadang Hadir:
Peluang ke Rajin Hadir: 0.8
Peluang ke Kadang Hadir: 0.2
Peluang ke Sering Absen: 0.5
Jumlah probabilitas dalam satu baris harus = 1

Dari state Sering Absen:
Peluang ke Rajin Hadir: 1.2
Peluang ke Kadang Hadir: 0.8
Peluang ke Sering Absen: 0.4
Jumlah probabilitas dalam satu baris harus = 1

Matriks Transisi:
[[1.  1.5 1.4]
 [0.8 0.2 0.5]
 [1.2 0.8 0.4]]

Distribusi Stasioner:
Rajin Hadir = 0.1230
Kadang Hadir = 0.3105
Sering Absen = 0.1500
